export const famousNames = [
  "elvis presley",
  "michael jackson",
  "princess diana",
  "taylor swift",
  "donald trump",
  "joe biden",
  "barack obama",
  "abraham lincoln",
  "john f kennedy",
  "marilyn monroe",
  "kobe bryant",
  "muhammad ali",
  "michael jordan",
  "tupac shakur",
  "whitney houston",
  "prince",
  "madonna",
  "elon musk",
  "steve jobs",
  "bill gates",
  "queen elizabeth",
  "king charles",
  "beyonce",
  "rihanna",
  "drake",
  "eminem",
  "john lennon",
  "paul mccartney",
  "freddie mercury",
  "frank sinatra",
  "robin williams",
  "heath ledger",
  "jimmy buffett",
  "bob marley",
  "lucille ball",
  "martin luther king",
  "nelson mandela",
  "pope francis",
];