-- ============================================================
-- Standalone Celebration of Life Presentations
-- Initial schema
-- September 13, 2026
--
-- This feature is intentionally separate from the existing
-- MyEMemorial Celebration of Life Presentation system.
--
-- Direct browser access is blocked with RLS. All reads/writes
-- will go through protected server API routes using the
-- Supabase service role.
-- ============================================================

create extension if not exists pgcrypto;


-- ============================================================
-- PRESENTATIONS
-- One record per standalone Celebration of Life Presentation.
-- ============================================================

create table if not exists public.celebration_presentations (
  id bigint generated by default as identity primary key,

  -- Safe non-sequential identifier that may be used in URLs.
  public_id uuid not null default gen_random_uuid() unique,

  -- Purchaser / creator information.
  customer_email text not null,

  -- Person being celebrated.
  person_name text not null,
  birth_date date,
  death_date date,
  featured_photo_url text,

  -- Simple presentation appearance.
  theme text not null default 'classic'
    check (theme in ('classic', 'warm', 'simple')),

  -- Presentation lifecycle.
  status text not null default 'draft'
    check (
      status in (
        'draft',
        'active',
        'expired',
        'converted',
        'cancelled'
      )
    ),

  -- Payment lifecycle.
  payment_status text not null default 'unpaid'
    check (
      payment_status in (
        'unpaid',
        'paid',
        'refunded',
        'failed'
      )
    ),

  -- Preserve the offer terms that existed when the customer
  -- created/purchased the presentation.
  price_cents integer not null default 1995
    check (price_cents >= 0),

  amount_paid_cents integer not null default 0
    check (amount_paid_cents >= 0),

  hosting_days integer not null default 60
    check (hosting_days > 0),

  stripe_checkout_session_id text unique,
  stripe_payment_intent_id text unique,

  -- Passwordless creator access.
  -- The raw edit token will never be stored here.
  -- Only its secure hash is stored.
  edit_token_hash text not null,

  -- Public presentation viewing token.
  -- This token is safe to place in a shareable presentation URL.
  public_share_token uuid not null default gen_random_uuid() unique,

  -- Family/friend contribution access.
  -- The raw contribution token will not be stored.
  contribution_token_hash text,
  contributions_enabled boolean not null default false,

  -- 60-day hosted presentation lifecycle.
  activated_at timestamptz,
  expires_at timestamptz,

  -- Offline/service backup.
  offline_backup_status text not null default 'not_requested'
    check (
      offline_backup_status in (
        'not_requested',
        'requested',
        'processing',
        'ready',
        'failed'
      )
    ),

  offline_backup_storage_path text,
  offline_backup_created_at timestamptz,
  offline_backup_error text,

  -- Soft, optional conversion into a permanent MyEMemorial.
  -- The original presentation remains traceable after conversion.
  converted_memorial_id bigint
    references public.memorials(id)
    on delete set null,

  converted_at timestamptz,

  -- Expiration email tracking.
  expiration_notice_14_sent_at timestamptz,
  expiration_notice_3_sent_at timestamptz,
  expiration_notice_expired_sent_at timestamptz,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint celebration_presentations_expiration_check
    check (
      expires_at is null
      or activated_at is null
      or expires_at >= activated_at
    )
);


-- ============================================================
-- PRESENTATION ITEMS
-- Photos and videos share ONE ordered timeline.
--
-- This allows:
-- Photo -> Video -> Photo -> Video
-- instead of the current presentation's photos-first/videos-last
-- behavior.
-- ============================================================

create table if not exists public.celebration_presentation_items (
  id bigint generated by default as identity primary key,

  presentation_id bigint not null
    references public.celebration_presentations(id)
    on delete cascade,

  item_type text not null
    check (item_type in ('photo', 'video')),

  -- Photo media.
  photo_url text,

  -- Storage path lets us later delete, retain, or transfer the
  -- original asset without depending only on a public URL.
  storage_path text,

  -- Video media.
  mux_asset_id text,
  mux_playback_id text,

  -- Optional for BOTH photos and videos.
  caption text not null default '',

  -- Used for family/friend contributions.
  attribution text not null default '',
  submitted_by_name text,
  submitted_by_email text,

  -- Creator items are normally immediately approved.
  -- Contributor items may remain pending until accepted.
  source text not null default 'creator'
    check (source in ('creator', 'contributor')),

  approval_status text not null default 'approved'
    check (
      approval_status in (
        'pending',
        'approved',
        'rejected'
      )
    ),

  -- One unified timeline.
  sort_order integer not null default 0
    check (sort_order >= 0),

  -- Useful for video-limit calculations and later conversion
  -- into a MyEMemorial.
  duration_seconds numeric(10, 2)
    check (
      duration_seconds is null
      or duration_seconds >= 0
    ),

  -- Soft deletion protects the creator from an accidental delete.
  -- The interface can simply say "Remove."
  removed_at timestamptz,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);


-- ============================================================
-- PRESENTATION MUSIC
-- Kept separate from photos/videos so songs do not become
-- presentation "slides."
-- ============================================================

create table if not exists public.celebration_presentation_music (
  id bigint generated by default as identity primary key,

  presentation_id bigint not null
    references public.celebration_presentations(id)
    on delete cascade,

  -- Allows us to support uploaded/licensed/library sources later
  -- without redesigning the table.
  source_type text not null
    check (
      source_type in (
        'uploaded',
        'youtube',
        'library'
      )
    ),

  source_url text not null,

  storage_path text,

  title text,
  artist text,

  sort_order integer not null default 0
    check (sort_order >= 0),

  removed_at timestamptz,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);


-- ============================================================
-- INDEXES
-- ============================================================

create index if not exists
  celebration_presentations_customer_email_idx
on public.celebration_presentations (
  lower(customer_email)
);


create index if not exists
  celebration_presentations_status_idx
on public.celebration_presentations (
  status
);


create index if not exists
  celebration_presentations_expires_at_idx
on public.celebration_presentations (
  expires_at
)
where expires_at is not null;


create index if not exists
  celebration_presentations_converted_memorial_idx
on public.celebration_presentations (
  converted_memorial_id
)
where converted_memorial_id is not null;


create index if not exists
  celebration_presentation_items_order_idx
on public.celebration_presentation_items (
  presentation_id,
  sort_order,
  id
)
where removed_at is null;


create index if not exists
  celebration_presentation_items_pending_idx
on public.celebration_presentation_items (
  presentation_id,
  approval_status
)
where
  source = 'contributor'
  and removed_at is null;


create index if not exists
  celebration_presentation_music_order_idx
on public.celebration_presentation_music (
  presentation_id,
  sort_order,
  id
)
where removed_at is null;


-- ============================================================
-- UPDATED_AT TRIGGERS
-- ============================================================

create or replace function public.set_celebration_presentation_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;


drop trigger if exists
  celebration_presentations_set_updated_at
on public.celebration_presentations;

create trigger celebration_presentations_set_updated_at
before update
on public.celebration_presentations
for each row
execute function public.set_celebration_presentation_updated_at();


drop trigger if exists
  celebration_presentation_items_set_updated_at
on public.celebration_presentation_items;

create trigger celebration_presentation_items_set_updated_at
before update
on public.celebration_presentation_items
for each row
execute function public.set_celebration_presentation_updated_at();


drop trigger if exists
  celebration_presentation_music_set_updated_at
on public.celebration_presentation_music;

create trigger celebration_presentation_music_set_updated_at
before update
on public.celebration_presentation_music
for each row
execute function public.set_celebration_presentation_updated_at();


-- ============================================================
-- SECURITY
--
-- No browser-facing policies are intentionally created.
-- Server API routes using SUPABASE_SERVICE_ROLE_KEY will perform
-- authorized reads and writes.
-- ============================================================

alter table public.celebration_presentations
  enable row level security;

alter table public.celebration_presentation_items
  enable row level security;

alter table public.celebration_presentation_music
  enable row level security;


-- ============================================================
-- TABLE DOCUMENTATION
-- ============================================================

comment on table public.celebration_presentations is
  'Standalone paid Celebration of Life presentations. Separate from memorial records until optionally converted into a MyEMemorial.';

comment on table public.celebration_presentation_items is
  'Ordered photo/video timeline for standalone Celebration of Life presentations, including optional captions and approved family contributions.';

comment on table public.celebration_presentation_music is
  'Background music selections for standalone Celebration of Life presentations.';